### ISSUE TITLE
Upgrade to webpack `.hooks` API

### ISSUE THREAD

**Issue by thompk2** [Appius/create-file-webpack#3]
this plugin uses `Tapable.plugin` which webpack has deprecated. Stacktrace below

```sh
(node:17285) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at CreateFilePlugin.apply (/Users/kit/toast/git-repos/new-project/node_modules/create-file-webpack/index.js:14:18)
    at webpack (/Users/kit/toast/git-repos/new-project/node_modules/webpack/lib/webpack.js:37:12)
    at module.exports (/Users/kit/toast/git-repos/new-project/server/webpack-dev-middleware.js:94:27)
    at getPort.then.actualPort (/Users/kit/toast/git-repos/new-project/server/index.js:98:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

For more information, see this comment in webpack: https://github.com/webpack/webpack/issues/6568#issuecomment-377491754

**Comment by Appius** [comment]
released version 1.0.2 with this fix inside
